controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
    resource:
        path: ../src/ApiResource/
        namespace: App\ApiResource
    type: attribute
api_login_check:
    path: /api/login_check